'use strict';

const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
const PDFDocument = require('pdfkit');
const Payment = require('../../models/Payment');
const Course = require('../../models/Course');
const User = require('../../models/User');
const asyncHandler = require('../../utils/asyncHandler');
const { sendSuccess, sendError } = require('../../utils/response');

const LOGO_PATH = path.join(__dirname, '..', '..', '..', 'assets', 'logo.png');
const BRAND = { primary: '#97F75F', bg: '#011110', ink: '#0B2E2C', muted: '#5B6B66', line: '#D8EBE0' };

const fmtDateTime = (d) => new Date(d).toLocaleString('en-NG', { dateStyle: 'medium', timeStyle: 'short' });
const money = (n, currency = 'NGN') => `${currency} ${Number(n || 0).toLocaleString('en-NG')}`;

/** GET /student/payments — the signed-in student's own payment history. */
const getMyPayments = asyncHandler(async (req, res) => {
  const payments = await Payment.find({ userId: req.user.id }).sort('-createdAt').limit(100).lean();

  const courseIds = payments.map((p) => p.courseId);
  const courses = courseIds.length ? await Course.find({ _id: { $in: courseIds } }).select('title').lean() : [];
  const titleById = new Map(courses.map((c) => [String(c._id), c.title]));

  sendSuccess(
    res,
    payments.map((p) => ({
      id: p._id,
      txRef: p.txRef,
      courseTitle: titleById.get(String(p.courseId)) || 'Course',
      amount: p.totalAmount ?? p.amount,
      baseAmount: p.baseAmount ?? p.amount,
      feeAmount: p.feeAmount ?? 0,
      currency: p.currency || 'NGN',
      status: p.status,
      createdAt: p.createdAt,
      paidAt: p.paidAt || null,
    }))
  );
});

/** Build a branded A4 payment receipt PDF as a Buffer. */
const buildReceiptPdf = ({ txRef, paidAt, studentName, studentEmail, courseTitle, baseAmount, feeAmount, totalAmount, currency, flwTransactionId }) =>
  new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 56 });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const W = doc.page.width;

      // Header band + real brand asset
      doc.rect(0, 0, W, 96).fill(BRAND.bg);
      if (fs.existsSync(LOGO_PATH)) {
        try { doc.image(LOGO_PATH, 56, 26, { width: 44, height: 44 }); } catch (_) { /* skip if unreadable */ }
      }
      doc.fillColor(BRAND.primary).font('Helvetica-Bold').fontSize(20).text('W3Skool', 112, 30);
      doc.fillColor('#F8FDF8').font('Helvetica-Bold').fontSize(14).text('Payment Receipt', 112, 56);
      doc.fillColor('#9DB4AC').font('Helvetica').fontSize(9).text('Thank you — your payment was successful.', 112, 76);

      let y = 132;
      const row = (label, value, opts = {}) => {
        doc.fillColor(BRAND.muted).font('Helvetica').fontSize(10).text(label, 56, y, { width: 170 });
        doc.fillColor(BRAND.ink).font(opts.bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(opts.bold ? 13 : 10)
          .text(String(value), 236, y, { width: W - 236 - 56 });
        y += opts.gap || 26;
      };

      doc.fillColor(BRAND.bg).font('Helvetica-Bold').fontSize(15).text('Transaction details', 56, y);
      y += 32;
      row('Receipt reference', txRef);
      row('Date paid', fmtDateTime(paidAt));
      row('Provider reference', flwTransactionId ? String(flwTransactionId) : '—');
      row('Student', studentName || '—');
      row('Email', studentEmail || '—');
      row('Course', courseTitle || '—');
      y += 4;
      doc.moveTo(56, y).lineTo(W - 56, y).lineWidth(1).strokeColor(BRAND.line).stroke();
      y += 20;
      row('Course price', money(baseAmount, currency));
      row('Processing fee', money(feeAmount, currency));
      row('Total paid', money(totalAmount, currency), { bold: true, gap: 32 });
      doc.moveTo(56, y).lineTo(W - 56, y).lineWidth(1).strokeColor(BRAND.line).stroke();
      y += 20;
      row('Status', 'Paid — verified', { gap: 30 });

      doc.fillColor(BRAND.muted).font('Helvetica').fontSize(9)
        .text('This receipt was generated by W3Skool for a payment processed by Flutterwave. Keep it for your records.', 56, doc.page.height - 84, { width: W - 112, align: 'center' });

      doc.end();
    } catch (e) {
      reject(e);
    }
  });

/** GET /student/payments/:id/receipt — verified payments only; streams a PDF attachment. */
const getReceipt = asyncHandler(async (req, res) => {
  const { id } = req.params;
  if (!mongoose.Types.ObjectId.isValid(id)) {
    return sendError(res, 'Payment not found.', 404, 'NOT_FOUND');
  }

  const payment = await Payment.findOne({ _id: id, userId: req.user.id }).lean();
  if (!payment) return sendError(res, 'Payment not found.', 404, 'NOT_FOUND');
  if (payment.status !== 'verified') {
    return sendError(res, 'Receipts are available only for successful payments.', 409, 'NOT_VERIFIED');
  }

  const [user, course] = await Promise.all([
    User.findById(payment.userId).select('name email').lean(),
    Course.findById(payment.courseId).select('title').lean(),
  ]);

  const buffer = await buildReceiptPdf({
    txRef: payment.txRef,
    paidAt: payment.paidAt || payment.createdAt,
    studentName: user?.name || '',
    studentEmail: user?.email || '',
    courseTitle: course?.title || 'W3Skool Course',
    baseAmount: payment.baseAmount ?? payment.amount,
    feeAmount: payment.feeAmount ?? 0,
    totalAmount: payment.totalAmount ?? payment.amount,
    currency: payment.currency || 'NGN',
    flwTransactionId: payment.flwTransactionId || null,
  });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="W3Skool-Receipt-${payment.txRef}.pdf"`);
  res.setHeader('Content-Length', buffer.length);
  return res.end(buffer);
});

module.exports = {
  getMyPayments,
  getReceipt,
};